// Barrel file — client-safe exports only
export { CashierTabs, type CashierTab } from './components/CashierTabs'
export { ActiveOrdersList } from './components/ActiveOrdersList'
export { OrderDetailPanel } from './components/OrderDetailPanel'
export { PaymentMethodSelect } from './components/PaymentMethodSelect'
export { PaymentReferenceInput } from './components/PaymentReferenceInput'
export { CancelOrderModal } from './components/CancelOrderModal'
export { CashierSkeleton } from './components/CashierSkeleton'
export { default as HistoryTable } from './components/HistoryTable'
export { useActiveOrders } from './hooks/useActiveOrders'
export { usePaymentMethods } from './hooks/usePaymentMethods'
export { useConfirmPayment } from './hooks/useConfirmPayment'
export { useCancelOrder } from './hooks/useCancelOrder'
export { useSalesHistory } from './hooks/useSalesHistory'
export { generarFactura, type FacturaData } from './api/generarFactura'
export type { CashierOrder, CashierOrderItem, PaymentMethod } from './types'
